global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['receitinha-api:8090']
